[package]
name = "copernica-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.5.9"
log = "0.4"
crossbeam-channel = "0.5.1"
chrono = "0.4.9"
