[package]
name = "copernica-protocols"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
copernica-common= { path = "../copernica-common" }
log = "0.4"
bincode = "1.3"
anyhow = "1.0"
